document.addEventListener("DOMContentLoaded",()=>{
 const db=firebase.firestore(),primaryAuth=firebase.auth(); const lista=document.getElementById("lista"), vazio=document.getElementById("vazio"), contador=document.getElementById("contador"), modal=document.getElementById("modal"), form=document.getElementById("form"), erro=document.getElementById("erro"), salvar=document.getElementById("salvar"); let lojaId=null, operadores=[];
 const abrir=()=>{erro.textContent="";form.reset();modal.hidden=false;modal.removeAttribute("hidden");setTimeout(()=>document.getElementById("nome").focus(),50)}; const fechar=()=>{modal.hidden=true;modal.setAttribute("hidden","")};
 document.getElementById("btnNovoOperador").onclick=abrir;document.getElementById("btnVazio").onclick=abrir;document.getElementById("fechar").onclick=fechar;modal.addEventListener("click",e=>{if(e.target===modal)fechar()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden)fechar()});
 function novoCodigo(){return String(Math.floor(1000+Math.random()*9000))} async function gerarCodigo(){for(let i=0;i<50;i++){const c=novoCodigo(),s=await db.collection("lojas").doc(lojaId).collection("operadores").doc(c).get();if(!s.exists)return c}throw new Error("Não foi possível gerar um código disponível.")}
 function emailTecnico(c){return `op-${lojaId}-${c}@gestokpdv.local`}
 function esc(v){return String(v??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[m]))}
 function render(){contador.textContent=`${operadores.length} ${operadores.length===1?"operador":"operadores"}`;vazio.style.display=operadores.length?"none":"block";lista.innerHTML=operadores.map(o=>`<div class="operator"><div class="operator-name"><div class="avatar">${esc((o.nome||"?").trim().charAt(0).toUpperCase())}</div><div><strong>${esc(o.nome)}</strong><small>Código ${esc(o.codigo)}</small></div></div><div><small>CÓDIGO</small><div class="code">${esc(o.codigo)}</div></div><div><span class="status ${o.ativo!==false?"on":"off"}">${o.ativo!==false?"Ativo":"Inativo"}</span></div><div class="actions"><button class="action" data-action="status" data-id="${o.codigo}">${o.ativo!==false?"Desativar":"Ativar"}</button></div></div>`).join("")}
 lista.addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.dataset.id,o=operadores.find(x=>x.codigo===id);if(!o)return;if(b.dataset.action==="status"){await db.collection("lojas").doc(lojaId).collection("operadores").doc(id).update({ativo:o.ativo===false,atualizadoEm:firebase.firestore.FieldValue.serverTimestamp()});toast(o.ativo===false?"Operador ativado.":"Operador desativado.")}});
 function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
 async function criarContaAuth(email,senha){const nomeApp=`gestok-op-${Date.now()}-${Math.random().toString(36).slice(2)}`;const app=firebase.initializeApp(firebaseConfig,nomeApp);try{const cred=await app.auth().createUserWithEmailAndPassword(email,senha);await app.auth().signOut();return cred.user.uid}finally{await app.delete()}}
 async function carregar(){const conta=obterContaGestok();lojaId=conta?.lojaId||obterLojaAtualGestok();if(!lojaId){alert("Não foi possível identificar a loja atual.");return}db.collection("lojas").doc(lojaId).collection("operadores").orderBy("criadoEm","desc").onSnapshot(s=>{operadores=s.docs.map(d=>({id:d.id,...d.data()}));render()},e=>{console.error(e);alert("Não foi possível carregar os operadores. Verifique as regras do Firebase.")})}
 form.addEventListener("submit",async e=>{e.preventDefault();erro.textContent="";const nome=document.getElementById("nome").value.trim(),senha=document.getElementById("senha").value,conf=document.getElementById("confirmar").value;if(!nome){erro.textContent="Informe o nome do operador.";return}if(senha.length<6){erro.textContent="A senha precisa ter pelo menos 6 caracteres.";return}if(senha!==conf){erro.textContent="As senhas não conferem.";return}salvar.disabled=true;salvar.textContent="Criando...";try{const codigo=await gerarCodigo(),email=emailTecnico(codigo),uid=await criarContaAuth(email,senha);await db.collection("lojas").doc(lojaId).collection("operadores").doc(codigo).set({codigo,nome,uid,email,ativo:true,criadoEm:firebase.firestore.FieldValue.serverTimestamp(),criadoPor:primaryAuth.currentUser.uid});await db.collection("acessos").doc(`${lojaId}_${codigo}`).set({uid,lojaId,codigo,operadorId:codigo,email,role:"operador"});await db.collection("acessos_uid").doc(uid).set({uid,lojaId,codigo,operadorId:codigo,role:"operador"});fechar();toast(`Operador criado. Código: ${codigo}`)}catch(e){console.error(e);erro.textContent=e.code==="auth/email-already-in-use"?"Este código já possui uma conta de acesso. Gere outro operador.":e.code==="permission-denied"?"O Firebase bloqueou o cadastro. Publique as novas regras do Firestore.":"Não foi possível cadastrar o operador."}finally{salvar.disabled=false;salvar.textContent="Criar operador"}});
 if(typeof observarAutenticacaoGestok==="function")observarAutenticacaoGestok(u=>{if(!u){location.replace("../login/index.html");return}carregar()});else primaryAuth.onAuthStateChanged(u=>{if(!u)location.replace("../login/index.html");else carregar()})
});
