document.addEventListener('DOMContentLoaded',()=>{
 const db=firebase.firestore(),primaryAuth=firebase.auth();
 const lista=document.getElementById('lista'), vazio=document.getElementById('vazio'), contador=document.getElementById('contador'), modal=document.getElementById('modal'), form=document.getElementById('form'), erro=document.getElementById('erro'), salvar=document.getElementById('salvar');
 let lojaId=null, operadores=[];
 const abrir=()=>{erro.textContent='';form.reset();modal.hidden=false;modal.removeAttribute('hidden');setTimeout(()=>document.getElementById('nome').focus(),50)};
 const fechar=()=>{modal.hidden=true;modal.setAttribute('hidden','')};
 document.getElementById('btnNovoOperador').onclick=abrir;document.getElementById('btnVazio').onclick=abrir;document.getElementById('fechar').onclick=fechar;modal.addEventListener('click',e=>{if(e.target===modal)fechar()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)fechar()});
 function novoCodigo(){return String(Math.floor(1000+Math.random()*9000))}
 async function gerarCodigo(){for(let i=0;i<50;i++){const c=novoCodigo(),s=await db.collection('lojas').doc(lojaId).collection('operadores').doc(c).get();if(!s.exists)return c}throw new Error('Não foi possível gerar um código disponível.')}
 function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
 function render(){contador.textContent=`${operadores.length} ${operadores.length===1?'operador':'operadores'}`;vazio.style.display=operadores.length?'none':'block';lista.innerHTML=operadores.map(o=>`<div class="operator"><div class="operator-name"><div class="avatar">${esc((o.nome||'?').trim().charAt(0).toUpperCase())}</div><div><strong>${esc(o.nome)}</strong><small>Código ${esc(o.codigo)}</small></div></div><div><small>CÓDIGO</small><div class="code">${esc(o.codigo)}</div></div><div><span class="status ${o.ativo!==false?'on':'off'}">${o.ativo!==false?'Ativo':'Inativo'}</span></div><div class="actions"><button class="action" data-action="status" data-id="${o.codigo}">${o.ativo!==false?'Desativar':'Ativar'}</button></div></div>`).join('')}
 lista.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id,o=operadores.find(x=>x.codigo===id);if(!o)return;if(b.dataset.action==='status'){await db.collection('lojas').doc(lojaId).collection('operadores').doc(id).update({ativo:o.ativo===false,atualizadoEm:firebase.firestore.FieldValue.serverTimestamp()});toast(o.ativo===false?'Operador ativado.':'Operador desativado.')}});
 function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
 async function hashSenha(senha,salt){const data=new TextEncoder().encode(`${salt}:${senha}`);if(!crypto?.subtle)throw new Error('SECURE_HASH_UNAVAILABLE');const digest=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
 function novoSalt(){const a=new Uint8Array(16);crypto.getRandomValues(a);return Array.from(a).map(b=>b.toString(16).padStart(2,'0')).join('')}
 async function carregar(){const conta=obterContaGestok();lojaId=conta?.lojaId||obterLojaAtualGestok();if(!lojaId){alert('Não foi possível identificar a loja atual.');return}db.collection('lojas').doc(lojaId).collection('operadores').orderBy('criadoEm','desc').onSnapshot(s=>{operadores=s.docs.map(d=>({id:d.id,...d.data()}));render()},e=>{console.error(e);alert('Não foi possível carregar os operadores. Verifique as regras do Firebase.')})}
 form.addEventListener('submit',async e=>{e.preventDefault();erro.textContent='';const nome=document.getElementById('nome').value.trim(),senha=document.getElementById('senha').value,conf=document.getElementById('confirmar').value;if(!nome){erro.textContent='Informe o nome do operador.';return}if(senha.length<4){erro.textContent='A senha precisa ter pelo menos 4 caracteres.';return}if(senha!==conf){erro.textContent='As senhas não conferem.';return}salvar.disabled=true;salvar.textContent='Criando...';try{const codigo=await gerarCodigo(),salt=novoSalt(),senhaHash=await hashSenha(senha,salt);await db.collection('lojas').doc(lojaId).collection('operadores').doc(codigo).set({codigo,nome,senhaHash,senhaSalt:salt,ativo:true,criadoEm:firebase.firestore.FieldValue.serverTimestamp(),criadoPor:primaryAuth.currentUser.uid});fechar();toast(`Operador criado. Código: ${codigo}`)}catch(e){console.error(e);erro.textContent=e.message==='SECURE_HASH_UNAVAILABLE'?'Abra o Gestok por HTTPS ou servidor local para gerar a senha com segurança.':e.code==='permission-denied'?'O Firebase bloqueou o cadastro. Publique as regras atualizadas.':'Não foi possível cadastrar o operador.'}finally{salvar.disabled=false;salvar.textContent='Criar operador'}});
 if(typeof observarAutenticacaoGestok==='function')observarAutenticacaoGestok(u=>{if(!u){location.replace('../login/index.html');return}carregar()});else primaryAuth.onAuthStateChanged(u=>{if(!u){location.replace('../login/index.html');return}carregar()})
});
